-- =============================================
-- Superseded: this file used to redefine Store_GetAll/Store_GetById/
-- Store_Insert/Store_Update with BranchId support against Inv.PharmacyStores.
--
-- It has been merged directly into Store_Procedures.sql, which now contains
-- the only definitions of these procedures. Having two files each redefine
-- the same procedures meant whichever one happened to execute last during
-- startup silently won - Store_Procedures.sql's older, BranchId-less
-- definitions were winning, breaking Store_GetAll/Store_Insert against
-- Pharmacy.PharmacyStores.BranchId (NOT NULL).
--
-- This file is intentionally left as a no-op rather than removed.
-- =============================================
